version: "3.8" #docker-compose versio
services:
  website:
    # Set the container name
    container_name: website_c

    # set name for the image
    image: website_i

    # Build the image using the Dockerfile in the current context
    build:
      context: .
      dockerfile: Dockerfile

      # Map host port 3000 to container port 3000
    ports:
      - "3000:3000" #<host_port>:<container_port/protocol_port>

    # Mount the current directory to /app in the container
    volumes:
      - .:/app
      - /app/node_modules

    # Specify the command to run when the container starts
    command: npm run dev
